import { NavItem } from 'types';

export const navItems: NavItem[] = [
  {
    title: 'Tableau de bord',
    url: '/dashboard',
    icon: 'dashboard',
    isActive: false,
    shortcut: ['d', 'd'],
    items: [],
  },
  {
    title: 'Agences',
    url: '/agencies',
    icon: 'agencies',
    isActive: false,
    shortcut: ['a', 'g'],
    items: [],
  },
  {
    title: 'Véhicules',
    url: '/vehicles',
    icon: 'vehicles',
    isActive: false,
    shortcut: ['v', 'v'],
    items: [],
  },
  {
    title: 'Clients',
    url: '/clients',
    icon: 'clients',
    isActive: false,
    shortcut: ['c', 'c'],
    items: [],
  },
  {
    title: 'Réservations',
    url: '/reservations',
    icon: 'reservations',
    isActive: false,
    shortcut: ['r', 'r'],
    items: [
      { title: 'Liste', url: '/reservations' },
      { title: 'Calendrier', url: '/reservations/calendar' },
    ],
  },
  {
    title: 'Facturation',
    url: '/billing',
    icon: 'invoicing',
    isActive: false,
    shortcut: ['b', 'b'],
    items: [],
  },
  {
    title: 'Dépenses',
    url: '/expenses',
    icon: 'billing',
    isActive: false,
    shortcut: ['d', 'p'],
    items: [],
  },
  {
    title: 'Assurances',
    url: '/insurances',
    icon: 'insurances',
    isActive: false,
    shortcut: ['i', 's'],
    items: [],
  },
  {
    title: 'Maintenances',
    url: '/maintenances',
    icon: 'maintenances',
    isActive: false,
    shortcut: ['m', 'm'],
    items: [],
  },
  {
    title: 'Visites techniques',
    url: '/technical-inspections',
    icon: 'technicalInspections',
    isActive: false,
    shortcut: ['t', 'i'],
    items: [],
  },
  {
    title: 'Vignettes',
    url: '/vignettes',
    icon: 'vignettes',
    isActive: false,
    shortcut: ['v', 'g'],
    items: [],
  },
  {
    title: 'Utilisateurs',
    url: '/users',
    icon: 'users',
    isActive: false,
    shortcut: ['u', 'u'],
    items: [],
  },
  {
    title: 'Rôles',
    url: '/roles',
    icon: 'roles',
    isActive: false,
    shortcut: ['r', 'o'],
    items: [],
  },
  {
    title: 'Notifications',
    url: '/notifications',
    icon: 'notifications',
    isActive: false,
    shortcut: ['n', 'n'],
    items: [],
  },
  {
    title: "Journal d'activité",
    url: '/logs',
    icon: 'logs',
    isActive: false,
    shortcut: ['l', 'g'],
    items: [],
  },
  {
    title: 'Paramètres',
    url: '/settings',
    icon: 'settings',
    isActive: false,
    shortcut: ['s', 's'],
    items: [],
  },
  {
    title: 'Rapports',
    url: '/reports',
    icon: 'billing',
    isActive: false,
    shortcut: ['r', 'p'],
    items: [],
  },
  {
    title: 'Site web',
    url: '/website',
    icon: 'globe',
    isActive: false,
    shortcut: ['w', 'b'],
    items: [],
  },
];
