const BASE = process.env.NEXT_PUBLIC_API_BASE_URL || 'http://127.0.0.1:8000/api/v1';

export const apiRoutes = {
  auth: {
    login: `${BASE}/auth/login`,
    logout: `${BASE}/auth/logout`,
    me: `${BASE}/auth/me`,
    refresh: `${BASE}/auth/refresh`,
    changePassword: `${BASE}/auth/change-password`,
    forgotPassword: `${BASE}/auth/forgot-password`,
    resetPassword: `${BASE}/auth/reset-password`,
  },
  agencies: {
    list: `${BASE}/agencies`,
    create: `${BASE}/agencies`,
    show: (id: string) => `${BASE}/agencies/${id}`,
    update: (id: string) => `${BASE}/agencies/${id}`,
    delete: (id: string) => `${BASE}/agencies/${id}`,
    restore: (id: string) => `${BASE}/agencies/${id}/restore`,
    logs: (id: string) => `${BASE}/agencies/${id}/logs`,
  },
  vehicles: {
    list: `${BASE}/vehicles`,
    create: `${BASE}/vehicles`,
    show: (id: string) => `${BASE}/vehicles/${id}`,
    update: (id: string) => `${BASE}/vehicles/${id}`,
    delete: (id: string) => `${BASE}/vehicles/${id}`,
    restore: (id: string) => `${BASE}/vehicles/${id}/restore`,
    updateStatus: (id: string) => `${BASE}/vehicles/${id}/status`,
    logs: (id: string) => `${BASE}/vehicles/${id}/logs`,
  },
  clients: {
    list: `${BASE}/clients`,
    create: `${BASE}/clients`,
    show: (id: string) => `${BASE}/clients/${id}`,
    update: (id: string) => `${BASE}/clients/${id}`,
    delete: (id: string) => `${BASE}/clients/${id}`,
    restore: (id: string) => `${BASE}/clients/${id}/restore`,
    logs: (id: string) => `${BASE}/clients/${id}/logs`,
  },
  reservations: {
    list: `${BASE}/reservations`,
    create: `${BASE}/reservations`,
    show: (id: string) => `${BASE}/reservations/${id}`,
    update: (id: string) => `${BASE}/reservations/${id}`,
    delete: (id: string) => `${BASE}/reservations/${id}`,
    confirm: (id: string) => `${BASE}/reservations/${id}/confirm`,
    activate: (id: string) => `${BASE}/reservations/${id}/activate`,
    complete: (id: string) => `${BASE}/reservations/${id}/complete`,
    cancel: (id: string) => `${BASE}/reservations/${id}/cancel`,
    calendar: `${BASE}/reservations/calendar`,
    statistics: `${BASE}/reservations/statistics`,
    logs: (id: string) => `${BASE}/reservations/${id}/logs`,
  },
  billing: {
    list: `${BASE}/billing`,
    create: `${BASE}/billing`,
    show: (id: string) => `${BASE}/billing/${id}`,
    update: (id: string) => `${BASE}/billing/${id}`,
    delete: (id: string) => `${BASE}/billing/${id}`,
    markPaid: (id: string) => `${BASE}/billing/${id}/mark-paid`,
    statistics: `${BASE}/billing/statistics`,
    logs: (id: string) => `${BASE}/billing/${id}/logs`,
  },
  insurances: {
    list: `${BASE}/insurances`,
    create: `${BASE}/insurances`,
    show: (id: string) => `${BASE}/insurances/${id}`,
    update: (id: string) => `${BASE}/insurances/${id}`,
    delete: (id: string) => `${BASE}/insurances/${id}`,
    restore: (id: string) => `${BASE}/insurances/${id}/restore`,
    logs: (id: string) => `${BASE}/insurances/${id}/logs`,
  },
  maintenances: {
    list: `${BASE}/maintenances`,
    create: `${BASE}/maintenances`,
    show: (id: string) => `${BASE}/maintenances/${id}`,
    update: (id: string) => `${BASE}/maintenances/${id}`,
    delete: (id: string) => `${BASE}/maintenances/${id}`,
    restore: (id: string) => `${BASE}/maintenances/${id}/restore`,
    updateStatus: (id: string) => `${BASE}/maintenances/${id}/status`,
    logs: (id: string) => `${BASE}/maintenances/${id}/logs`,
  },
  technicalInspections: {
    list: `${BASE}/technical-inspections`,
    create: `${BASE}/technical-inspections`,
    show: (id: string) => `${BASE}/technical-inspections/${id}`,
    update: (id: string) => `${BASE}/technical-inspections/${id}`,
    delete: (id: string) => `${BASE}/technical-inspections/${id}`,
    restore: (id: string) => `${BASE}/technical-inspections/${id}/restore`,
    logs: (id: string) => `${BASE}/technical-inspections/${id}/logs`,
  },
  vignettes: {
    list: `${BASE}/vignettes`,
    create: `${BASE}/vignettes`,
    show: (id: string) => `${BASE}/vignettes/${id}`,
    update: (id: string) => `${BASE}/vignettes/${id}`,
    delete: (id: string) => `${BASE}/vignettes/${id}`,
    restore: (id: string) => `${BASE}/vignettes/${id}/restore`,
    markPaid: (id: string) => `${BASE}/vignettes/${id}/mark-paid`,
    logs: (id: string) => `${BASE}/vignettes/${id}/logs`,
  },
  users: {
    list: `${BASE}/users`,
    create: `${BASE}/users`,
    show: (id: string) => `${BASE}/users/${id}`,
    update: (id: string) => `${BASE}/users/${id}`,
    delete: (id: string) => `${BASE}/users/${id}`,
    restore: (id: string) => `${BASE}/users/${id}/restore`,
    activate: (id: string) => `${BASE}/users/${id}/activate`,
    suspend: (id: string) => `${BASE}/users/${id}/suspend`,
    assignRole: (id: string) => `${BASE}/users/${id}/roles`,
    profile: `${BASE}/users/profile`,
    updateProfile: `${BASE}/users/profile`,
    logs: (id: string) => `${BASE}/users/${id}/logs`,
  },
  roles: {
    list: `${BASE}/roles`,
    create: `${BASE}/roles`,
    show: (id: string) => `${BASE}/roles/${id}`,
    update: (id: string) => `${BASE}/roles/${id}`,
    delete: (id: string) => `${BASE}/roles/${id}`,
    assignPermissions: (id: string) => `${BASE}/roles/${id}/permissions`,
  },
  permissions: {
    list: `${BASE}/permissions`,
  },
  notifications: {
    list: `${BASE}/notifications`,
    send: `${BASE}/notifications`,
    show: (id: string) => `${BASE}/notifications/${id}`,
    markRead: (id: string) => `${BASE}/notifications/${id}/read`,
    markAllRead: `${BASE}/notifications/read-all`,
    summary: `${BASE}/notifications/summary`,
    delete: (id: string) => `${BASE}/notifications/${id}`,
  },
  logs: {
    list: `${BASE}/logs`,
    show: (id: string) => `${BASE}/logs/${id}`,
  },
  files: {
    uploadTemp: `${BASE}/files/upload-temp`,
    cleanupTemp: `${BASE}/files/cleanup-temp`,
  },
  dashboard: {
    statistics: `${BASE}/dashboard/statistics`,
  },
  settings: {
    all: `${BASE}/settings`,
    group: (group: string) => `${BASE}/settings/${group}`,
    updateGroup: (group: string) => `${BASE}/settings/${group}`,
    uploadLogo: `${BASE}/settings/logo`,
    uploadHeroImage: `${BASE}/settings/hero-image`,
  },
  website: {
    stats: `${BASE}/website/stats`,
    reservations: `${BASE}/website/reservations`,
    showReservation: (id: string) => `${BASE}/website/reservations/${id}`,
    approveReservation: (id: string) => `${BASE}/website/reservations/${id}/approve`,
    rejectReservation: (id: string) => `${BASE}/website/reservations/${id}/reject`,
    vehicles: `${BASE}/website/vehicles`,
    updateVehicle: (id: string) => `${BASE}/website/vehicles/${id}`,
  },
  public: {
    company: `${BASE}/public/company`,
    vehicles: `${BASE}/public/vehicles`,
    vehicle: (id: string) => `${BASE}/public/vehicles/${id}`,
    submitReservation: `${BASE}/public/reservations`,
  },
  expenses: {
    list: `${BASE}/expenses`,
    create: `${BASE}/expenses`,
    show: (id: string) => `${BASE}/expenses/${id}`,
    update: (id: string) => `${BASE}/expenses/${id}`,
    delete: (id: string) => `${BASE}/expenses/${id}`,
    statistics: `${BASE}/expenses/statistics`,
  },
  payments: {
    list: (reservationId: string) => `${BASE}/reservations/${reservationId}/payments`,
    create: (reservationId: string) => `${BASE}/reservations/${reservationId}/payments`,
    delete: (reservationId: string, paymentId: string) => `${BASE}/reservations/${reservationId}/payments/${paymentId}`,
  },
  // Extended routes
  vehiclesExt: {
    photos: (id: string) => `${BASE}/vehicles/${id}/photos`,
    media: (id: string) => `${BASE}/vehicles/${id}/media`,
    deleteMedia: (id: string, mediaId: string | number) => `${BASE}/vehicles/${id}/media/${mediaId}`,
    registrationCard: (id: string) => `${BASE}/vehicles/${id}/registration-card`,
    documents: (id: string) => `${BASE}/vehicles/${id}/documents`,
    history: (id: string) => `${BASE}/vehicles/${id}/history`,
    vehicleReservations: (id: string) => `${BASE}/vehicles/${id}/reservations`,
    statistics: (id: string) => `${BASE}/vehicles/${id}/statistics`,
    expenses: (id: string) => `${BASE}/vehicles/${id}/expenses`,
  },
  agenciesExt: {
    statistics: (id: string) => `${BASE}/agencies/${id}/statistics`,
  },
  clientsExt: {
    statistics: (id: string) => `${BASE}/clients/${id}/statistics`,
    reservations: (id: string) => `${BASE}/clients/${id}/reservations`,
  },
  reservationsExt: {
    confirm: (id: string) => `${BASE}/reservations/${id}/confirm`,
    contract: (id: string) => `${BASE}/reservations/${id}/contract/pdf`,
    uploadContract: (id: string) => `${BASE}/reservations/${id}/contract`,
    uploadPickupPhotos: (id: string) => `${BASE}/reservations/${id}/pickup-photos`,
    uploadReturnPhotos: (id: string) => `${BASE}/reservations/${id}/return-photos`,
    noShow: (id: string) => `${BASE}/reservations/${id}/no-show`,
    extend: (id: string) => `${BASE}/reservations/${id}/extend`,
    overdue: `${BASE}/reservations/overdue`,
    credits: `${BASE}/reservations/credits`,
    checkConflict: `${BASE}/reservations/check-conflict`,
  },
  profile: {
    show:            `${BASE}/profile`,
    update:          `${BASE}/profile`,
    uploadAvatar:    `${BASE}/profile/avatar`,
    uploadSignature: `${BASE}/profile/signature`,
    uploadStamp:     `${BASE}/profile/stamp`,
    deleteSignature: `${BASE}/profile/signature`,
    deleteStamp:     `${BASE}/profile/stamp`,
  },
  maintenancesExt: {
    complete: (id: string) => `${BASE}/maintenances/${id}/complete`,
    cancel: (id: string) => `${BASE}/maintenances/${id}/cancel`,
    scheduled: `${BASE}/maintenances/scheduled`,
    overdue: `${BASE}/maintenances/overdue`,
    uploadInvoices: (id: string) => `${BASE}/maintenances/${id}/invoices`,
    uploadPhotosBefore: (id: string) => `${BASE}/maintenances/${id}/photos-before`,
    uploadPhotosAfter: (id: string) => `${BASE}/maintenances/${id}/photos-after`,
    deleteMedia: (id: string, mediaId: string | number) => `${BASE}/maintenances/${id}/media/${mediaId}`,
  },
  billingExt: {
    approve: (id: string) => `${BASE}/billing/${id}/approve`,
    viewPdf: (id: string) => `${BASE}/billing/${id}/pdf/view`,
    downloadPdf: (id: string) => `${BASE}/billing/${id}/pdf/download`,
    fromReservation: (reservationId: string) => `${BASE}/billing/from-reservation/${reservationId}`,
    restore: (id: string) => `${BASE}/billing/${id}/restore`,
  },
  claims: {
    list:        `${BASE}/claims`,
    create:      `${BASE}/claims`,
    statistics:  `${BASE}/claims/statistics`,
    show:        (id: string) => `${BASE}/claims/${id}`,
    update:      (id: string) => `${BASE}/claims/${id}`,
    delete:      (id: string) => `${BASE}/claims/${id}`,
    updateStatus:(id: string) => `${BASE}/claims/${id}/status`,
    uploadPhotos:(id: string) => `${BASE}/claims/${id}/photos`,
    uploadDocs:  (id: string) => `${BASE}/claims/${id}/documents`,
    uploadInsuranceDocs: (id: string) => `${BASE}/claims/${id}/insurance-documents`,
    deleteMedia: (id: string, mediaId: number) => `${BASE}/claims/${id}/media/${mediaId}`,
  },
  oilChangeAlerts: `${BASE}/maintenances/oil-change/alerts`,
  documentsExt: {
    maintenance:         (id: string) => `${BASE}/maintenances/${id}/documents`,
    insurance:           (id: string) => `${BASE}/insurances/${id}/documents`,
    technicalInspection: (id: string) => `${BASE}/technical-inspections/${id}/documents`,
    vignette:            (id: string) => `${BASE}/vignettes/${id}/documents`,
    expense:             (id: string) => `${BASE}/expenses/${id}/documents`,
    mediaDelete: {
      maintenance:         (id: string, mid: number) => `${BASE}/maintenances/${id}/media/${mid}`,
      insurance:           (id: string, mid: number) => `${BASE}/insurances/${id}/media/${mid}`,
      technicalInspection: (id: string, mid: number) => `${BASE}/technical-inspections/${id}/media/${mid}`,
      vignette:            (id: string, mid: number) => `${BASE}/vignettes/${id}/media/${mid}`,
    },
  },
} as const;
