import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconMoon,
  IconDotsVertical,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconX,
  IconBrandGithub,
  IconCalendar,
  IconClock,
  IconCar,
  IconReceipt,
  IconUsers,
  IconBuilding,
  IconTool,
  IconShield,
  IconBell,
  IconKey,
  IconHistory,
  IconFileInvoice,
  IconClipboardCheck,
  IconId,
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  spinner: IconLoader2,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  check: IconCheck,
  calendar: IconCalendar,
  clock: IconClock,
  receipt: IconReceipt,
  users: IconUsers,
  agencies: IconBuilding,
  vehicles: IconCar,
  clients: IconId,
  reservations: IconCalendar,
  invoicing: IconFileInvoice,
  insurances: IconShield,
  maintenances: IconTool,
  technicalInspections: IconClipboardCheck,
  vignettes: IconReceipt,
  notifications: IconBell,
  roles: IconKey,
  logs: IconHistory,
};
